# Generated by Django 4.2.17 on 2025-11-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquevisitor',
            name='session_key',
        ),
        migrations.AddField(
            model_name='uniquevisitor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
