# Generated by Django 5.1.7 on 2025-06-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='woman.jpg', upload_to='profile_pics'),
        ),
    ]
