# Generated by Django 5.1.7 on 2025-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='section',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
