# Generated by Django 5.1.7 on 2025-06-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
