# Generated by Django 5.1.7 on 2025-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WomenInSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the person or item.', max_length=100)),
                ('picture', models.ImageField(help_text='An image for the profile.', upload_to='profile_pictures/')),
                ('description', models.TextField(help_text='A detailed description for the profile.')),
            ],
            options={
                'verbose_name': 'WomenInSpotlight',
                'verbose_name_plural': 'WomenInSpotlight',
            },
        ),
    ]
